name: project_kobe_client
description: A new Flutter project.
version: 0.0.1
author: KOBE
homepage: 

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"

dependencies:
  meta: ">=1.1.1 <2.0.0"
  redux: ">=4.0.0 <5.0.0"
  json_serializable: ^3.3.0
  redux_remote_devtools: ^2.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^1.0.0
  pedantic: 1.8.0+1
  flutter_redux: ^0.6.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the Icons class.
  uses-material-design: true
  fonts:
    - family: Gotham
      fonts:
        - asset: fonts/GothamRounded-Light.ttf
        - asset: fonts/GothamRounded-Medium.ttf

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/.

  # To add assets from package dependencies, first ensure the asset
  # is in the lib/ directory of the dependency. Then,
  # refer to the asset with a path prefixed with
  # `packages/PACKAGE_NAME/`. The `lib/` is implied, do not
  # include `lib/` in the asset path.
  #
  # Here is an example:
  #
  # assets:
  #  - packages/PACKAGE_NAME/path/to/asset

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro

